<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Linear Regression | An Introduction to Statistical Learning</title>
  <meta name="description" content="3 Linear Regression | An Introduction to Statistical Learning" />
  <meta name="generator" content="bookdown 0.42.1 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Linear Regression | An Introduction to Statistical Learning" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Linear Regression | An Introduction to Statistical Learning" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="statistical-learning.html"/>
<link rel="next" href="classification.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="islrv2.css" type="text/css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/aaaakshat/cm-web-fonts@latest/fonts.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ISLRv2 Solutions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="statistical-learning.html"><a href="statistical-learning.html"><i class="fa fa-check"></i><b>2</b> Statistical Learning</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statistical-learning.html"><a href="statistical-learning.html#conceptual"><i class="fa fa-check"></i><b>2.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-learning.html"><a href="statistical-learning.html#question-1"><i class="fa fa-check"></i><b>2.1.1</b> Question 1</a></li>
<li class="chapter" data-level="2.1.2" data-path="statistical-learning.html"><a href="statistical-learning.html#question-2"><i class="fa fa-check"></i><b>2.1.2</b> Question 2</a></li>
<li class="chapter" data-level="2.1.3" data-path="statistical-learning.html"><a href="statistical-learning.html#question-3"><i class="fa fa-check"></i><b>2.1.3</b> Question 3</a></li>
<li class="chapter" data-level="2.1.4" data-path="statistical-learning.html"><a href="statistical-learning.html#question-4"><i class="fa fa-check"></i><b>2.1.4</b> Question 4</a></li>
<li class="chapter" data-level="2.1.5" data-path="statistical-learning.html"><a href="statistical-learning.html#question-5"><i class="fa fa-check"></i><b>2.1.5</b> Question 5</a></li>
<li class="chapter" data-level="2.1.6" data-path="statistical-learning.html"><a href="statistical-learning.html#question-6"><i class="fa fa-check"></i><b>2.1.6</b> Question 6</a></li>
<li class="chapter" data-level="2.1.7" data-path="statistical-learning.html"><a href="statistical-learning.html#question-7"><i class="fa fa-check"></i><b>2.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-learning.html"><a href="statistical-learning.html#applied"><i class="fa fa-check"></i><b>2.2</b> Applied</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-learning.html"><a href="statistical-learning.html#question-8"><i class="fa fa-check"></i><b>2.2.1</b> Question 8</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-learning.html"><a href="statistical-learning.html#question-9"><i class="fa fa-check"></i><b>2.2.2</b> Question 9</a></li>
<li class="chapter" data-level="2.2.3" data-path="statistical-learning.html"><a href="statistical-learning.html#question-10"><i class="fa fa-check"></i><b>2.2.3</b> Question 10</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>3</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="linear-regression.html"><a href="linear-regression.html#conceptual-1"><i class="fa fa-check"></i><b>3.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="linear-regression.html"><a href="linear-regression.html#question-1-1"><i class="fa fa-check"></i><b>3.1.1</b> Question 1</a></li>
<li class="chapter" data-level="3.1.2" data-path="linear-regression.html"><a href="linear-regression.html#question-2-1"><i class="fa fa-check"></i><b>3.1.2</b> Question 2</a></li>
<li class="chapter" data-level="3.1.3" data-path="linear-regression.html"><a href="linear-regression.html#question-3-1"><i class="fa fa-check"></i><b>3.1.3</b> Question 3</a></li>
<li class="chapter" data-level="3.1.4" data-path="linear-regression.html"><a href="linear-regression.html#question-4-1"><i class="fa fa-check"></i><b>3.1.4</b> Question 4</a></li>
<li class="chapter" data-level="3.1.5" data-path="linear-regression.html"><a href="linear-regression.html#question-5-1"><i class="fa fa-check"></i><b>3.1.5</b> Question 5</a></li>
<li class="chapter" data-level="3.1.6" data-path="linear-regression.html"><a href="linear-regression.html#question-6-1"><i class="fa fa-check"></i><b>3.1.6</b> Question 6</a></li>
<li class="chapter" data-level="3.1.7" data-path="linear-regression.html"><a href="linear-regression.html#question-7-1"><i class="fa fa-check"></i><b>3.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="linear-regression.html"><a href="linear-regression.html#applied-1"><i class="fa fa-check"></i><b>3.2</b> Applied</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="linear-regression.html"><a href="linear-regression.html#question-8-1"><i class="fa fa-check"></i><b>3.2.1</b> Question 8</a></li>
<li class="chapter" data-level="3.2.2" data-path="linear-regression.html"><a href="linear-regression.html#question-9-1"><i class="fa fa-check"></i><b>3.2.2</b> Question 9</a></li>
<li class="chapter" data-level="3.2.3" data-path="linear-regression.html"><a href="linear-regression.html#question-10-1"><i class="fa fa-check"></i><b>3.2.3</b> Question 10</a></li>
<li class="chapter" data-level="3.2.4" data-path="linear-regression.html"><a href="linear-regression.html#question-11"><i class="fa fa-check"></i><b>3.2.4</b> Question 11</a></li>
<li class="chapter" data-level="3.2.5" data-path="linear-regression.html"><a href="linear-regression.html#question-12"><i class="fa fa-check"></i><b>3.2.5</b> Question 12</a></li>
<li class="chapter" data-level="3.2.6" data-path="linear-regression.html"><a href="linear-regression.html#question-13"><i class="fa fa-check"></i><b>3.2.6</b> Question 13</a></li>
<li class="chapter" data-level="3.2.7" data-path="linear-regression.html"><a href="linear-regression.html#question-14"><i class="fa fa-check"></i><b>3.2.7</b> Question 14</a></li>
<li class="chapter" data-level="3.2.8" data-path="linear-regression.html"><a href="linear-regression.html#question-15"><i class="fa fa-check"></i><b>3.2.8</b> Question 15</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>4</b> Classification</a>
<ul>
<li class="chapter" data-level="4.1" data-path="classification.html"><a href="classification.html#conceptual-2"><i class="fa fa-check"></i><b>4.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="classification.html"><a href="classification.html#question-1-2"><i class="fa fa-check"></i><b>4.1.1</b> Question 1</a></li>
<li class="chapter" data-level="4.1.2" data-path="classification.html"><a href="classification.html#question-2-2"><i class="fa fa-check"></i><b>4.1.2</b> Question 2</a></li>
<li class="chapter" data-level="4.1.3" data-path="classification.html"><a href="classification.html#question-3-2"><i class="fa fa-check"></i><b>4.1.3</b> Question 3</a></li>
<li class="chapter" data-level="4.1.4" data-path="classification.html"><a href="classification.html#question-4-2"><i class="fa fa-check"></i><b>4.1.4</b> Question 4</a></li>
<li class="chapter" data-level="4.1.5" data-path="classification.html"><a href="classification.html#question-5-2"><i class="fa fa-check"></i><b>4.1.5</b> Question 5</a></li>
<li class="chapter" data-level="4.1.6" data-path="classification.html"><a href="classification.html#question-6-2"><i class="fa fa-check"></i><b>4.1.6</b> Question 6</a></li>
<li class="chapter" data-level="4.1.7" data-path="classification.html"><a href="classification.html#question-7-2"><i class="fa fa-check"></i><b>4.1.7</b> Question 7</a></li>
<li class="chapter" data-level="4.1.8" data-path="classification.html"><a href="classification.html#question-8-2"><i class="fa fa-check"></i><b>4.1.8</b> Question 8</a></li>
<li class="chapter" data-level="4.1.9" data-path="classification.html"><a href="classification.html#question-9-2"><i class="fa fa-check"></i><b>4.1.9</b> Question 9</a></li>
<li class="chapter" data-level="4.1.10" data-path="classification.html"><a href="classification.html#question-10-2"><i class="fa fa-check"></i><b>4.1.10</b> Question 10</a></li>
<li class="chapter" data-level="4.1.11" data-path="classification.html"><a href="classification.html#question-11-1"><i class="fa fa-check"></i><b>4.1.11</b> Question 11</a></li>
<li class="chapter" data-level="4.1.12" data-path="classification.html"><a href="classification.html#question-12-1"><i class="fa fa-check"></i><b>4.1.12</b> Question 12</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="classification.html"><a href="classification.html#applied-2"><i class="fa fa-check"></i><b>4.2</b> Applied</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="classification.html"><a href="classification.html#question-13-1"><i class="fa fa-check"></i><b>4.2.1</b> Question 13</a></li>
<li class="chapter" data-level="4.2.2" data-path="classification.html"><a href="classification.html#question-14-1"><i class="fa fa-check"></i><b>4.2.2</b> Question 14</a></li>
<li class="chapter" data-level="4.2.3" data-path="classification.html"><a href="classification.html#question-15-1"><i class="fa fa-check"></i><b>4.2.3</b> Question 15</a></li>
<li class="chapter" data-level="4.2.4" data-path="classification.html"><a href="classification.html#question-13-2"><i class="fa fa-check"></i><b>4.2.4</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="resampling-methods.html"><a href="resampling-methods.html"><i class="fa fa-check"></i><b>5</b> Resampling Methods</a>
<ul>
<li class="chapter" data-level="5.1" data-path="resampling-methods.html"><a href="resampling-methods.html#conceptual-3"><i class="fa fa-check"></i><b>5.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="resampling-methods.html"><a href="resampling-methods.html#question-1-3"><i class="fa fa-check"></i><b>5.1.1</b> Question 1</a></li>
<li class="chapter" data-level="5.1.2" data-path="resampling-methods.html"><a href="resampling-methods.html#question-2-3"><i class="fa fa-check"></i><b>5.1.2</b> Question 2</a></li>
<li class="chapter" data-level="5.1.3" data-path="resampling-methods.html"><a href="resampling-methods.html#question-3-3"><i class="fa fa-check"></i><b>5.1.3</b> Question 3</a></li>
<li class="chapter" data-level="5.1.4" data-path="resampling-methods.html"><a href="resampling-methods.html#question-4-3"><i class="fa fa-check"></i><b>5.1.4</b> Question 4</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="resampling-methods.html"><a href="resampling-methods.html#applied-3"><i class="fa fa-check"></i><b>5.2</b> Applied</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="resampling-methods.html"><a href="resampling-methods.html#question-5-3"><i class="fa fa-check"></i><b>5.2.1</b> Question 5</a></li>
<li class="chapter" data-level="5.2.2" data-path="resampling-methods.html"><a href="resampling-methods.html#question-6-3"><i class="fa fa-check"></i><b>5.2.2</b> Question 6</a></li>
<li class="chapter" data-level="5.2.3" data-path="resampling-methods.html"><a href="resampling-methods.html#question-7-3"><i class="fa fa-check"></i><b>5.2.3</b> Question 7</a></li>
<li class="chapter" data-level="5.2.4" data-path="resampling-methods.html"><a href="resampling-methods.html#question-8-3"><i class="fa fa-check"></i><b>5.2.4</b> Question 8</a></li>
<li class="chapter" data-level="5.2.5" data-path="resampling-methods.html"><a href="resampling-methods.html#question-9-3"><i class="fa fa-check"></i><b>5.2.5</b> Question 9</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html"><i class="fa fa-check"></i><b>6</b> Linear Model Selection and Regularization</a>
<ul>
<li class="chapter" data-level="6.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#conceptual-4"><i class="fa fa-check"></i><b>6.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-1-4"><i class="fa fa-check"></i><b>6.1.1</b> Question 1</a></li>
<li class="chapter" data-level="6.1.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-2-4"><i class="fa fa-check"></i><b>6.1.2</b> Question 2</a></li>
<li class="chapter" data-level="6.1.3" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-3-4"><i class="fa fa-check"></i><b>6.1.3</b> Question 3</a></li>
<li class="chapter" data-level="6.1.4" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-4-4"><i class="fa fa-check"></i><b>6.1.4</b> Question 4</a></li>
<li class="chapter" data-level="6.1.5" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-5-4"><i class="fa fa-check"></i><b>6.1.5</b> Question 5</a></li>
<li class="chapter" data-level="6.1.6" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-6-4"><i class="fa fa-check"></i><b>6.1.6</b> Question 6</a></li>
<li class="chapter" data-level="6.1.7" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-7-4"><i class="fa fa-check"></i><b>6.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#applied-4"><i class="fa fa-check"></i><b>6.2</b> Applied</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-8-4"><i class="fa fa-check"></i><b>6.2.1</b> Question 8</a></li>
<li class="chapter" data-level="6.2.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-9-4"><i class="fa fa-check"></i><b>6.2.2</b> Question 9</a></li>
<li class="chapter" data-level="6.2.3" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-10-3"><i class="fa fa-check"></i><b>6.2.3</b> Question 10</a></li>
<li class="chapter" data-level="6.2.4" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-11-2"><i class="fa fa-check"></i><b>6.2.4</b> Question 11</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html"><i class="fa fa-check"></i><b>7</b> Moving Beyond Linearity</a>
<ul>
<li class="chapter" data-level="7.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#conceptual-5"><i class="fa fa-check"></i><b>7.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-1-5"><i class="fa fa-check"></i><b>7.1.1</b> Question 1</a></li>
<li class="chapter" data-level="7.1.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-2-5"><i class="fa fa-check"></i><b>7.1.2</b> Question 2</a></li>
<li class="chapter" data-level="7.1.3" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-3-5"><i class="fa fa-check"></i><b>7.1.3</b> Question 3</a></li>
<li class="chapter" data-level="7.1.4" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-4-5"><i class="fa fa-check"></i><b>7.1.4</b> Question 4</a></li>
<li class="chapter" data-level="7.1.5" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-5-5"><i class="fa fa-check"></i><b>7.1.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#applied-5"><i class="fa fa-check"></i><b>7.2</b> Applied</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-6-5"><i class="fa fa-check"></i><b>7.2.1</b> Question 6</a></li>
<li class="chapter" data-level="7.2.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-7-5"><i class="fa fa-check"></i><b>7.2.2</b> Question 7</a></li>
<li class="chapter" data-level="7.2.3" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-8-5"><i class="fa fa-check"></i><b>7.2.3</b> Question 8</a></li>
<li class="chapter" data-level="7.2.4" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-9-5"><i class="fa fa-check"></i><b>7.2.4</b> Question 9</a></li>
<li class="chapter" data-level="7.2.5" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-10-4"><i class="fa fa-check"></i><b>7.2.5</b> Question 10</a></li>
<li class="chapter" data-level="7.2.6" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-11-3"><i class="fa fa-check"></i><b>7.2.6</b> Question 11</a></li>
<li class="chapter" data-level="7.2.7" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-12-2"><i class="fa fa-check"></i><b>7.2.7</b> Question 12</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tree-based-methods.html"><a href="tree-based-methods.html"><i class="fa fa-check"></i><b>8</b> Tree-Based Methods</a>
<ul>
<li class="chapter" data-level="8.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#conceptual-6"><i class="fa fa-check"></i><b>8.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-1-6"><i class="fa fa-check"></i><b>8.1.1</b> Question 1</a></li>
<li class="chapter" data-level="8.1.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-2-6"><i class="fa fa-check"></i><b>8.1.2</b> Question 2</a></li>
<li class="chapter" data-level="8.1.3" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-3-6"><i class="fa fa-check"></i><b>8.1.3</b> Question 3</a></li>
<li class="chapter" data-level="8.1.4" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-4-6"><i class="fa fa-check"></i><b>8.1.4</b> Question 4</a></li>
<li class="chapter" data-level="8.1.5" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-5-6"><i class="fa fa-check"></i><b>8.1.5</b> Question 5</a></li>
<li class="chapter" data-level="8.1.6" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-6-6"><i class="fa fa-check"></i><b>8.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#applied-6"><i class="fa fa-check"></i><b>8.2</b> Applied</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-7-6"><i class="fa fa-check"></i><b>8.2.1</b> Question 7</a></li>
<li class="chapter" data-level="8.2.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-8-6"><i class="fa fa-check"></i><b>8.2.2</b> Question 8</a></li>
<li class="chapter" data-level="8.2.3" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-9-6"><i class="fa fa-check"></i><b>8.2.3</b> Question 9</a></li>
<li class="chapter" data-level="8.2.4" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-10-5"><i class="fa fa-check"></i><b>8.2.4</b> Question 10</a></li>
<li class="chapter" data-level="8.2.5" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-11-4"><i class="fa fa-check"></i><b>8.2.5</b> Question 11</a></li>
<li class="chapter" data-level="8.2.6" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-12-3"><i class="fa fa-check"></i><b>8.2.6</b> Question 12</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>9</b> Support Vector Machines</a>
<ul>
<li class="chapter" data-level="9.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#conceptual-7"><i class="fa fa-check"></i><b>9.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-1-7"><i class="fa fa-check"></i><b>9.1.1</b> Question 1</a></li>
<li class="chapter" data-level="9.1.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-2-7"><i class="fa fa-check"></i><b>9.1.2</b> Question 2</a></li>
<li class="chapter" data-level="9.1.3" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-3-7"><i class="fa fa-check"></i><b>9.1.3</b> Question 3</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#applied-7"><i class="fa fa-check"></i><b>9.2</b> Applied</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-4-7"><i class="fa fa-check"></i><b>9.2.1</b> Question 4</a></li>
<li class="chapter" data-level="9.2.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-5-7"><i class="fa fa-check"></i><b>9.2.2</b> Question 5</a></li>
<li class="chapter" data-level="9.2.3" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-6-7"><i class="fa fa-check"></i><b>9.2.3</b> Question 6</a></li>
<li class="chapter" data-level="9.2.4" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-7-7"><i class="fa fa-check"></i><b>9.2.4</b> Question 7</a></li>
<li class="chapter" data-level="9.2.5" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-8-7"><i class="fa fa-check"></i><b>9.2.5</b> Question 8</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="deep-learning.html"><a href="deep-learning.html"><i class="fa fa-check"></i><b>10</b> Deep Learning</a>
<ul>
<li class="chapter" data-level="10.1" data-path="deep-learning.html"><a href="deep-learning.html#conceptual-8"><i class="fa fa-check"></i><b>10.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="deep-learning.html"><a href="deep-learning.html#question-1-8"><i class="fa fa-check"></i><b>10.1.1</b> Question 1</a></li>
<li class="chapter" data-level="10.1.2" data-path="deep-learning.html"><a href="deep-learning.html#question-2-8"><i class="fa fa-check"></i><b>10.1.2</b> Question 2</a></li>
<li class="chapter" data-level="10.1.3" data-path="deep-learning.html"><a href="deep-learning.html#question-3-8"><i class="fa fa-check"></i><b>10.1.3</b> Question 3</a></li>
<li class="chapter" data-level="10.1.4" data-path="deep-learning.html"><a href="deep-learning.html#question-4-8"><i class="fa fa-check"></i><b>10.1.4</b> Question 4</a></li>
<li class="chapter" data-level="10.1.5" data-path="deep-learning.html"><a href="deep-learning.html#question-5-8"><i class="fa fa-check"></i><b>10.1.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="deep-learning.html"><a href="deep-learning.html#applied-8"><i class="fa fa-check"></i><b>10.2</b> Applied</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="deep-learning.html"><a href="deep-learning.html#question-6-8"><i class="fa fa-check"></i><b>10.2.1</b> Question 6</a></li>
<li class="chapter" data-level="10.2.2" data-path="deep-learning.html"><a href="deep-learning.html#question-7-8"><i class="fa fa-check"></i><b>10.2.2</b> Question 7</a></li>
<li class="chapter" data-level="10.2.3" data-path="deep-learning.html"><a href="deep-learning.html#question-8-8"><i class="fa fa-check"></i><b>10.2.3</b> Question 8</a></li>
<li class="chapter" data-level="10.2.4" data-path="deep-learning.html"><a href="deep-learning.html#question-9-7"><i class="fa fa-check"></i><b>10.2.4</b> Question 9</a></li>
<li class="chapter" data-level="10.2.5" data-path="deep-learning.html"><a href="deep-learning.html#question-10-6"><i class="fa fa-check"></i><b>10.2.5</b> Question 10</a></li>
<li class="chapter" data-level="10.2.6" data-path="deep-learning.html"><a href="deep-learning.html#question-11-5"><i class="fa fa-check"></i><b>10.2.6</b> Question 11</a></li>
<li class="chapter" data-level="10.2.7" data-path="deep-learning.html"><a href="deep-learning.html#question-12-4"><i class="fa fa-check"></i><b>10.2.7</b> Question 12</a></li>
<li class="chapter" data-level="10.2.8" data-path="deep-learning.html"><a href="deep-learning.html#question-13-3"><i class="fa fa-check"></i><b>10.2.8</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html"><i class="fa fa-check"></i><b>11</b> Survival Analysis and Censored Data</a>
<ul>
<li class="chapter" data-level="11.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#conceptual-9"><i class="fa fa-check"></i><b>11.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-1-9"><i class="fa fa-check"></i><b>11.1.1</b> Question 1</a></li>
<li class="chapter" data-level="11.1.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-2-9"><i class="fa fa-check"></i><b>11.1.2</b> Question 2</a></li>
<li class="chapter" data-level="11.1.3" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-3-9"><i class="fa fa-check"></i><b>11.1.3</b> Question 3</a></li>
<li class="chapter" data-level="11.1.4" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-4-9"><i class="fa fa-check"></i><b>11.1.4</b> Question 4</a></li>
<li class="chapter" data-level="11.1.5" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-5-9"><i class="fa fa-check"></i><b>11.1.5</b> Question 5</a></li>
<li class="chapter" data-level="11.1.6" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-6-9"><i class="fa fa-check"></i><b>11.1.6</b> Question 6</a></li>
<li class="chapter" data-level="11.1.7" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-7-9"><i class="fa fa-check"></i><b>11.1.7</b> Question 7</a></li>
<li class="chapter" data-level="11.1.8" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-8-9"><i class="fa fa-check"></i><b>11.1.8</b> Question 8</a></li>
<li class="chapter" data-level="11.1.9" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-9-8"><i class="fa fa-check"></i><b>11.1.9</b> Question 9</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#applied-9"><i class="fa fa-check"></i><b>11.2</b> Applied</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-10-7"><i class="fa fa-check"></i><b>11.2.1</b> Question 10</a></li>
<li class="chapter" data-level="11.2.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-11-6"><i class="fa fa-check"></i><b>11.2.2</b> Question 11</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html"><i class="fa fa-check"></i><b>12</b> Unsupervised Learning</a>
<ul>
<li class="chapter" data-level="12.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#conceptual-10"><i class="fa fa-check"></i><b>12.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-1-10"><i class="fa fa-check"></i><b>12.1.1</b> Question 1</a></li>
<li class="chapter" data-level="12.1.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-2-10"><i class="fa fa-check"></i><b>12.1.2</b> Question 2</a></li>
<li class="chapter" data-level="12.1.3" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-3-10"><i class="fa fa-check"></i><b>12.1.3</b> Question 3</a></li>
<li class="chapter" data-level="12.1.4" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-4-10"><i class="fa fa-check"></i><b>12.1.4</b> Question 4</a></li>
<li class="chapter" data-level="12.1.5" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-5-10"><i class="fa fa-check"></i><b>12.1.5</b> Question 5</a></li>
<li class="chapter" data-level="12.1.6" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-6-10"><i class="fa fa-check"></i><b>12.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#applied-10"><i class="fa fa-check"></i><b>12.2</b> Applied</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-7-10"><i class="fa fa-check"></i><b>12.2.1</b> Question 7</a></li>
<li class="chapter" data-level="12.2.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-8-10"><i class="fa fa-check"></i><b>12.2.2</b> Question 8</a></li>
<li class="chapter" data-level="12.2.3" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-9-9"><i class="fa fa-check"></i><b>12.2.3</b> Question 9</a></li>
<li class="chapter" data-level="12.2.4" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-10-8"><i class="fa fa-check"></i><b>12.2.4</b> Question 10</a></li>
<li class="chapter" data-level="12.2.5" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-11-7"><i class="fa fa-check"></i><b>12.2.5</b> Question 11</a></li>
<li class="chapter" data-level="12.2.6" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-12-5"><i class="fa fa-check"></i><b>12.2.6</b> Question 12</a></li>
<li class="chapter" data-level="12.2.7" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-13-4"><i class="fa fa-check"></i><b>12.2.7</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="multiple-testing.html"><a href="multiple-testing.html"><i class="fa fa-check"></i><b>13</b> Multiple Testing</a>
<ul>
<li class="chapter" data-level="13.1" data-path="multiple-testing.html"><a href="multiple-testing.html#conceptual-11"><i class="fa fa-check"></i><b>13.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="multiple-testing.html"><a href="multiple-testing.html#question-1-11"><i class="fa fa-check"></i><b>13.1.1</b> Question 1</a></li>
<li class="chapter" data-level="13.1.2" data-path="multiple-testing.html"><a href="multiple-testing.html#question-2-11"><i class="fa fa-check"></i><b>13.1.2</b> Question 2</a></li>
<li class="chapter" data-level="13.1.3" data-path="multiple-testing.html"><a href="multiple-testing.html#question-3-11"><i class="fa fa-check"></i><b>13.1.3</b> Question 3</a></li>
<li class="chapter" data-level="13.1.4" data-path="multiple-testing.html"><a href="multiple-testing.html#question-4-11"><i class="fa fa-check"></i><b>13.1.4</b> Question 4</a></li>
<li class="chapter" data-level="13.1.5" data-path="multiple-testing.html"><a href="multiple-testing.html#question-5-11"><i class="fa fa-check"></i><b>13.1.5</b> Question 5</a></li>
<li class="chapter" data-level="13.1.6" data-path="multiple-testing.html"><a href="multiple-testing.html#question-6-11"><i class="fa fa-check"></i><b>13.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="multiple-testing.html"><a href="multiple-testing.html#applied-11"><i class="fa fa-check"></i><b>13.2</b> Applied</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="multiple-testing.html"><a href="multiple-testing.html#question-7-11"><i class="fa fa-check"></i><b>13.2.1</b> Question 7</a></li>
<li class="chapter" data-level="13.2.2" data-path="multiple-testing.html"><a href="multiple-testing.html#question-8-11"><i class="fa fa-check"></i><b>13.2.2</b> Question 8</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Statistical Learning</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Linear Regression<a href="linear-regression.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="conceptual-1" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Conceptual<a href="linear-regression.html#conceptual-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="question-1-1" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Question 1<a href="linear-regression.html#question-1-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Describe the null hypotheses to which the _p_values given in Table 3.4
correspond. Explain what conclusions you can draw based on these _p_values.
Your explanation should be phrased in terms of <code>sales</code>, <code>TV</code>, <code>radio</code>, and
<code>newspaper</code>, rather than in terms of the coefficients of the linear model.</p>
</blockquote>
</div>
<div id="question-2-1" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Question 2<a href="linear-regression.html#question-2-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Carefully explain the differences between the KNN classifier and KNN
regression methods.</p>
</blockquote>
</div>
<div id="question-3-1" class="section level3 hasAnchor" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Question 3<a href="linear-regression.html#question-3-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Suppose we have a data set with five predictors, <span class="math inline">\(X_1\)</span> = GPA, <span class="math inline">\(X_2\)</span> = IQ,
<span class="math inline">\(X_3\)</span> = Level (1 for College and 0 for High School), <span class="math inline">\(X_4\)</span> = Interaction
between GPA and IQ, and <span class="math inline">\(X_5\)</span> = Interaction between GPA and Level. The
response is starting salary after graduation (in thousands of dollars).
Suppose we use least squares to fit the model, and get <span class="math inline">\(\hat\beta_0 = 50\)</span>,
<span class="math inline">\(\hat\beta_1 = 20\)</span>, <span class="math inline">\(\hat\beta_2 = 0.07\)</span>, <span class="math inline">\(\hat\beta_3 = 35\)</span>, <span class="math inline">\(\hat\beta_4 = 0.01\)</span>, <span class="math inline">\(\hat\beta_5 = -10\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Which answer is correct, and why?</p>
<ol style="list-style-type: lower-roman">
<li>For a fixed value of IQ and GPA, high school graduates earn more on
average than college graduates.</li>
<li>For a fixed value of IQ and GPA, college graduates earn more on
average than high school graduates.</li>
<li>For a fixed value of IQ and GPA, high school graduates earn more on
average than college graduates provided that the GPA is high enough.</li>
<li>For a fixed value of IQ and GPA, college graduates earn more on
average than high school graduates provided that the GPA is high
enough.</li>
</ol></li>
<li><p>Predict the salary of a college graduate with IQ of 110 and a GPA of 4.0.</p></li>
<li><p>True or false: Since the coefficient for the GPA/IQ interaction term is
very small, there is very little evidence of an interaction effect. Justify
your answer.</p></li>
</ol>
</blockquote>
</div>
<div id="question-4-1" class="section level3 hasAnchor" number="3.1.4">
<h3><span class="header-section-number">3.1.4</span> Question 4<a href="linear-regression.html#question-4-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>I collect a set of data (<span class="math inline">\(n = 100\)</span> observations) containing a single predictor
and a quantitative response. I then fit a linear regression model to the data,
as well as a separate cubic regression, i.e. <span class="math inline">\(Y = \beta_0 + \beta_1X + \beta_2X^2 + \beta_3X^3 + \epsilon\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Suppose that the true relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is linear,
i.e. <span class="math inline">\(Y = \beta_0 + \beta_1X + \epsilon\)</span>. Consider the training residual
sum of squares (RSS) for the linear regression, and also the training RSS
for the cubic regression. Would we expect one to be lower than the other,
would we expect them to be the same, or is there not enough information to
tell? Justify your answer.</p></li>
<li><p>Answer (a) using test rather than training RSS.</p></li>
<li><p>Suppose that the true relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is not linear, but
we don’t know how far it is from linear. Consider the training RSS for the
linear regression, and also the training RSS for the cubic regression.
Would we expect one to be lower than the other, would we expect them to be
the same, or is there not enough information to tell? Justify your answer.</p></li>
<li><p>Answer (c) using test rather than training RSS.</p></li>
</ol>
</blockquote>
</div>
<div id="question-5-1" class="section level3 hasAnchor" number="3.1.5">
<h3><span class="header-section-number">3.1.5</span> Question 5<a href="linear-regression.html#question-5-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Consider the fitted values that result from performing linear regression
without an intercept. In this setting, the ith fitted value takes the form
<span class="math display">\[\hat{y}_i = x_i\hat\beta,\]</span>
where
<span class="math display">\[\hat{\beta} = \left(\sum_{i=1}^nx_iy_i\right) / \left(\sum_{i&#39; = 1}^n x^2_{i&#39;}\right).\]</span>
show that we can write
<span class="math display">\[\hat{y}_i = \sum_{i&#39; = 1}^na_{i&#39;}y_{i&#39;}\]</span>
What is <span class="math inline">\(a_{i&#39;}\)</span>?</p>
<p><em>Note: We interpret this result by saying that the fitted
values from linear regression are linear combinations of the response values.</em></p>
</blockquote>
</div>
<div id="question-6-1" class="section level3 hasAnchor" number="3.1.6">
<h3><span class="header-section-number">3.1.6</span> Question 6<a href="linear-regression.html#question-6-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Using (3.4), argue that in the case of simple linear regression, the
least squares line always passes through the point <span class="math inline">\((\bar{x}, \bar{y})\)</span>.</p>
</blockquote>
</div>
<div id="question-7-1" class="section level3 hasAnchor" number="3.1.7">
<h3><span class="header-section-number">3.1.7</span> Question 7<a href="linear-regression.html#question-7-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>It is claimed in the text that in the case of simple linear regression
of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span>, the <span class="math inline">\(R^2\)</span> statistic (3.17) is equal to the square of the
correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> (3.18). Prove that this is the case. For
simplicity, you may assume that <span class="math inline">\(\bar{x} = \bar{y} = 0\)</span>.</p>
</blockquote>
</div>
</div>
<div id="applied-1" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Applied<a href="linear-regression.html#applied-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="question-8-1" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Question 8<a href="linear-regression.html#question-8-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This question involves the use of simple linear regression on the Auto
data set.</p>
<ol style="list-style-type: lower-alpha">
<li>Use the <code>lm()</code> function to perform a simple linear regression with <code>mpg</code> as
the response and <code>horsepower</code> as the predictor. Use the <code>summary()</code> function
to print the results. Comment on the output. For example:</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="linear-regression.html#cb107-1" tabindex="-1"></a>Auto <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/Auto.data&quot;</span>, <span class="at">na.strings =</span> <span class="st">&quot;?&quot;</span>, <span class="at">stringsAsFactors =</span> T, <span class="at">header =</span> T)</span>
<span id="cb107-2"><a href="linear-regression.html#cb107-2" tabindex="-1"></a>Auto <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(Auto)</span>
<span id="cb107-3"><a href="linear-regression.html#cb107-3" tabindex="-1"></a><span class="fu">attach</span>(Auto)</span>
<span id="cb107-4"><a href="linear-regression.html#cb107-4" tabindex="-1"></a>lm.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> horsepower)</span>
<span id="cb107-5"><a href="linear-regression.html#cb107-5" tabindex="-1"></a><span class="fu">summary</span>(lm.fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ horsepower)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.5710  -3.2592  -0.3435   2.7630  16.9240 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 39.935861   0.717499   55.66   &lt;2e-16 ***
## horsepower  -0.157845   0.006446  -24.49   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.906 on 390 degrees of freedom
## Multiple R-squared:  0.6059, Adjusted R-squared:  0.6049 
## F-statistic: 599.7 on 1 and 390 DF,  p-value: &lt; 2.2e-16</code></pre>
<blockquote>
<ol style="list-style-type: lower-roman">
<li>Is there a relationship between the predictor and the response?</li>
</ol>
</blockquote>
<p>Yes. The p-value for the t-statistic for horsepower is extremely low, which suggests a relationship.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-roman">
<li>How strong is the relationship between the predictor and the response?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="linear-regression.html#cb109-1" tabindex="-1"></a><span class="fu">mean</span>(mpg)</span></code></pre></div>
<pre><code>## [1] 23.44592</code></pre>
<p>The RSE is 4.906 while the mean value of the response is 23.44592.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="linear-regression.html#cb111-1" tabindex="-1"></a><span class="fu">sigma</span>(lm.fit)<span class="sc">/</span><span class="fu">mean</span>(mpg)</span></code></pre></div>
<pre><code>## [1] 0.2092371</code></pre>
<p>This suggests a roughly 21% percentage error.</p>
<p>The <span class="math inline">\(R^2\)</span> statistic is 0.6059 so our predictor explains 60.59% of the variance in the response.</p>
<blockquote>
<ol start="3" style="list-style-type: lower-roman">
<li>Is the relationship between the predictor and the response positive or
negative?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="linear-regression.html#cb113-1" tabindex="-1"></a><span class="fu">coef</span>(lm.fit)[[<span class="st">&quot;horsepower&quot;</span>]]</span></code></pre></div>
<pre><code>## [1] -0.1578447</code></pre>
<p>The coefficient is less than 0, so the relationship is negative.
&gt; iv. What is the predicted mpg associated with a horsepower of 98?</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="linear-regression.html#cb115-1" tabindex="-1"></a><span class="fu">predict</span>(lm.fit, <span class="fu">data.frame</span>(<span class="at">horsepower =</span> <span class="dv">98</span>))[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 24.46708</code></pre>
<blockquote>
<ol start="22" style="list-style-type: lower-alpha">
<li>What are the associated 95% confidence and prediction intervals?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="linear-regression.html#cb117-1" tabindex="-1"></a><span class="fu">predict</span>(lm.fit, <span class="fu">data.frame</span>(<span class="at">horsepower =</span> <span class="dv">98</span>), <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 24.46708 23.97308 24.96108</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="linear-regression.html#cb119-1" tabindex="-1"></a><span class="fu">predict</span>(lm.fit, <span class="fu">data.frame</span>(<span class="at">horsepower =</span> <span class="dv">98</span>), <span class="at">interval =</span> <span class="st">&quot;prediction&quot;</span>)</span></code></pre></div>
<pre><code>##        fit     lwr      upr
## 1 24.46708 14.8094 34.12476</code></pre>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Plot the response and the predictor. Use the <code>abline()</code> function to display
the least squares regression line.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="linear-regression.html#cb121-1" tabindex="-1"></a><span class="fu">plot</span>(horsepower, mpg, <span class="at">pch =</span> <span class="dv">20</span>)</span>
<span id="cb121-2"><a href="linear-regression.html#cb121-2" tabindex="-1"></a><span class="fu">abline</span>(lm.fit, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use the <code>plot()</code> function to produce diagnostic plots of the least squares
regression fit. Comment on any problems you see with the fit.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="linear-regression.html#cb122-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(lm.fit), <span class="fu">residuals</span>(lm.fit), <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">xlab =</span> <span class="st">&quot;Fitted values&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-8-1.png" width="672" />
There appears to be some evidence of non-linearity as it looks like there is a relationship between the fitted values and residuals.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="linear-regression.html#cb123-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(lm.fit), <span class="fu">rstudent</span>(lm.fit), <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">xlab =</span> <span class="st">&quot;Fitted values&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Studentised residuals&quot;</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>There are some data points with studentised residuals above 3 - these are possible outliers.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="linear-regression.html#cb124-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">hatvalues</span>(lm.fit), <span class="fu">rstudent</span>(lm.fit), <span class="at">pch=</span><span class="dv">20</span>, <span class="at">xlab =</span> <span class="st">&quot;Leverage&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Studentised residuals&quot;</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-10-1.png" width="672" />
There are a few very high leverage points, however none are outside the studentised residual range of 3 to -3.</p>
</div>
<div id="question-9-1" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Question 9<a href="linear-regression.html#question-9-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This question involves the use of multiple linear regression on the <code>Auto</code>
data set.</p>
<ol style="list-style-type: lower-alpha">
<li>Produce a scatterplot matrix which includes all of the variables in the
data set.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="linear-regression.html#cb125-1" tabindex="-1"></a><span class="fu">pairs</span>(Auto, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">cex=</span><span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Compute the matrix of correlations between the variables using the function
<code>cor()</code>. You will need to exclude the name variable, <code>name</code> which is
qualitative.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="linear-regression.html#cb126-1" tabindex="-1"></a><span class="fu">cor</span>(Auto[,<span class="sc">!</span>(<span class="fu">names</span>(Auto) <span class="sc">%in%</span> <span class="st">&quot;name&quot;</span>)])</span></code></pre></div>
<pre><code>##                     mpg  cylinders displacement horsepower     weight
## mpg           1.0000000 -0.7776175   -0.8051269 -0.7784268 -0.8322442
## cylinders    -0.7776175  1.0000000    0.9508233  0.8429834  0.8975273
## displacement -0.8051269  0.9508233    1.0000000  0.8972570  0.9329944
## horsepower   -0.7784268  0.8429834    0.8972570  1.0000000  0.8645377
## weight       -0.8322442  0.8975273    0.9329944  0.8645377  1.0000000
## acceleration  0.4233285 -0.5046834   -0.5438005 -0.6891955 -0.4168392
## year          0.5805410 -0.3456474   -0.3698552 -0.4163615 -0.3091199
## origin        0.5652088 -0.5689316   -0.6145351 -0.4551715 -0.5850054
##              acceleration       year     origin
## mpg             0.4233285  0.5805410  0.5652088
## cylinders      -0.5046834 -0.3456474 -0.5689316
## displacement   -0.5438005 -0.3698552 -0.6145351
## horsepower     -0.6891955 -0.4163615 -0.4551715
## weight         -0.4168392 -0.3091199 -0.5850054
## acceleration    1.0000000  0.2903161  0.2127458
## year            0.2903161  1.0000000  0.1815277
## origin          0.2127458  0.1815277  1.0000000</code></pre>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use the <code>lm()</code> function to perform a multiple linear regression with <code>mpg</code>
as the response and all other variables except name as the predictors. Use
the <code>summary()</code> function to print the results. Comment on the output. For
instance:</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="linear-regression.html#cb128-1" tabindex="-1"></a>lm.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> . <span class="sc">-</span> name, <span class="at">data =</span> Auto)</span>
<span id="cb128-2"><a href="linear-regression.html#cb128-2" tabindex="-1"></a><span class="fu">summary</span>(lm.fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ . - name, data = Auto)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.5903 -2.1565 -0.1169  1.8690 13.0604 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -17.218435   4.644294  -3.707  0.00024 ***
## cylinders     -0.493376   0.323282  -1.526  0.12780    
## displacement   0.019896   0.007515   2.647  0.00844 ** 
## horsepower    -0.016951   0.013787  -1.230  0.21963    
## weight        -0.006474   0.000652  -9.929  &lt; 2e-16 ***
## acceleration   0.080576   0.098845   0.815  0.41548    
## year           0.750773   0.050973  14.729  &lt; 2e-16 ***
## origin         1.426141   0.278136   5.127 4.67e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.328 on 384 degrees of freedom
## Multiple R-squared:  0.8215, Adjusted R-squared:  0.8182 
## F-statistic: 252.4 on 7 and 384 DF,  p-value: &lt; 2.2e-16</code></pre>
<blockquote>
<ol style="list-style-type: lower-roman">
<li>Is there a relationship between the predictors and the response?</li>
</ol>
</blockquote>
<p>Yes, as the p-value calculated from the F-test is very low.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-roman">
<li>Which predictors appear to have a statistically significant relationship
to the response?</li>
</ol>
</blockquote>
<p><code>displacement</code>, <code>weight</code>, <code>year</code>, and <code>origin</code>.</p>
<blockquote>
<ol start="3" style="list-style-type: lower-roman">
<li>What does the coefficient for the <code>year</code> variable suggest?</li>
</ol>
</blockquote>
<p><code>year</code> and <code>mpg</code> have a positive relationship, so the later a car is produced, the higher its miles per gallon.</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Use the <code>plot()</code> function to produce diagnostic plots of the linear
regression fit. Comment on any problems you see with the fit. Do the
residual plots suggest any unusually large outliers? Does the leverage plot
identify any observations with unusually high leverage?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="linear-regression.html#cb130-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(lm.fit), <span class="fu">residuals</span>(lm.fit), <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">xlab =</span> <span class="st">&quot;Fitted values&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-14-1.png" width="672" />
There seems to be some kind of non-linearity in our dataset as the residuals seem to have some relationship with the fitted values.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="linear-regression.html#cb131-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(lm.fit), <span class="fu">rstudent</span>(lm.fit), <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">xlab =</span> <span class="st">&quot;Fitted values&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Studentised residuals&quot;</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-15-1.png" width="672" />
There are quite a few high residual values; their studentised residual values are above 3 which indicates an outlier.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="linear-regression.html#cb132-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">hatvalues</span>(lm.fit), <span class="fu">rstudent</span>(lm.fit), <span class="at">pch=</span><span class="dv">20</span>, <span class="at">xlab =</span> <span class="st">&quot;Leverage&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Studentised residuals&quot;</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="linear-regression.html#cb133-1" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">hatvalues</span>(lm.fit))</span></code></pre></div>
<pre><code>## [1] 0.1899129</code></pre>
<p>There is a very high leverage point with a leverage of 0.19.</p>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>Use the <code>*</code> and <code>:</code> symbols to fit linear regression models with
interaction effects. Do any interactions appear to be statistically
significant?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="linear-regression.html#cb135-1" tabindex="-1"></a>lm.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> (. <span class="sc">-</span> name) <span class="sc">*</span> (. <span class="sc">-</span> name), <span class="at">data =</span> Auto)</span>
<span id="cb135-2"><a href="linear-regression.html#cb135-2" tabindex="-1"></a><span class="fu">summary</span>(lm.fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ (. - name) * (. - name), data = Auto)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.6303 -1.4481  0.0596  1.2739 11.1386 
## 
## Coefficients:
##                             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)                3.548e+01  5.314e+01   0.668  0.50475   
## cylinders                  6.989e+00  8.248e+00   0.847  0.39738   
## displacement              -4.785e-01  1.894e-01  -2.527  0.01192 * 
## horsepower                 5.034e-01  3.470e-01   1.451  0.14769   
## weight                     4.133e-03  1.759e-02   0.235  0.81442   
## acceleration              -5.859e+00  2.174e+00  -2.696  0.00735 **
## year                       6.974e-01  6.097e-01   1.144  0.25340   
## origin                    -2.090e+01  7.097e+00  -2.944  0.00345 **
## cylinders:displacement    -3.383e-03  6.455e-03  -0.524  0.60051   
## cylinders:horsepower       1.161e-02  2.420e-02   0.480  0.63157   
## cylinders:weight           3.575e-04  8.955e-04   0.399  0.69000   
## cylinders:acceleration     2.779e-01  1.664e-01   1.670  0.09584 . 
## cylinders:year            -1.741e-01  9.714e-02  -1.793  0.07389 . 
## cylinders:origin           4.022e-01  4.926e-01   0.816  0.41482   
## displacement:horsepower   -8.491e-05  2.885e-04  -0.294  0.76867   
## displacement:weight        2.472e-05  1.470e-05   1.682  0.09342 . 
## displacement:acceleration -3.479e-03  3.342e-03  -1.041  0.29853   
## displacement:year          5.934e-03  2.391e-03   2.482  0.01352 * 
## displacement:origin        2.398e-02  1.947e-02   1.232  0.21875   
## horsepower:weight         -1.968e-05  2.924e-05  -0.673  0.50124   
## horsepower:acceleration   -7.213e-03  3.719e-03  -1.939  0.05325 . 
## horsepower:year           -5.838e-03  3.938e-03  -1.482  0.13916   
## horsepower:origin          2.233e-03  2.930e-02   0.076  0.93931   
## weight:acceleration        2.346e-04  2.289e-04   1.025  0.30596   
## weight:year               -2.245e-04  2.127e-04  -1.056  0.29182   
## weight:origin             -5.789e-04  1.591e-03  -0.364  0.71623   
## acceleration:year          5.562e-02  2.558e-02   2.174  0.03033 * 
## acceleration:origin        4.583e-01  1.567e-01   2.926  0.00365 **
## year:origin                1.393e-01  7.399e-02   1.882  0.06062 . 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.695 on 363 degrees of freedom
## Multiple R-squared:  0.8893, Adjusted R-squared:  0.8808 
## F-statistic: 104.2 on 28 and 363 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Adding all possible interaction terms, <code>acceleration:origin</code> seems to be the one with the highest statistical significance. <code>acceleration:year</code> and <code>displacement:year</code> are also below the 0.05 level of significance, so should likely be included as well.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="linear-regression.html#cb137-1" tabindex="-1"></a>lm.fitnoint <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> . <span class="sc">-</span> name, <span class="at">data =</span> Auto)</span>
<span id="cb137-2"><a href="linear-regression.html#cb137-2" tabindex="-1"></a>lm.fitint <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> . <span class="sc">-</span> name <span class="sc">+</span> acceleration<span class="sc">:</span>origin <span class="sc">+</span> acceleration<span class="sc">:</span>year <span class="sc">+</span> displacement<span class="sc">:</span>year, <span class="at">data =</span> Auto)</span>
<span id="cb137-3"><a href="linear-regression.html#cb137-3" tabindex="-1"></a></span>
<span id="cb137-4"><a href="linear-regression.html#cb137-4" tabindex="-1"></a><span class="fu">anova</span>(lm.fitnoint, lm.fitint)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: mpg ~ (cylinders + displacement + horsepower + weight + acceleration + 
##     year + origin + name) - name
## Model 2: mpg ~ (cylinders + displacement + horsepower + weight + acceleration + 
##     year + origin + name) - name + acceleration:origin + acceleration:year + 
##     displacement:year
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    384 4252.2                                  
## 2    381 3457.6  3    794.63 29.188 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The ANOVA test shows that including these interaction terms significantly increases the fit of the model.</p>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>Try a few different transformations of the variables, such as <span class="math inline">\(log(X)\)</span>,
<span class="math inline">\(\sqrt{X}\)</span>, <span class="math inline">\(X^2\)</span>. Comment on your findings.</li>
</ol>
</blockquote>
<p>Let’s look at <code>horsepower</code>:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="linear-regression.html#cb139-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb139-2"><a href="linear-regression.html#cb139-2" tabindex="-1"></a><span class="fu">plot</span>(horsepower, mpg, <span class="at">pch =</span> <span class="dv">20</span>)</span>
<span id="cb139-3"><a href="linear-regression.html#cb139-3" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(horsepower), mpg, <span class="at">pch =</span> <span class="dv">20</span>)</span>
<span id="cb139-4"><a href="linear-regression.html#cb139-4" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">sqrt</span>(horsepower), mpg, <span class="at">pch =</span> <span class="dv">20</span>)</span>
<span id="cb139-5"><a href="linear-regression.html#cb139-5" tabindex="-1"></a><span class="fu">plot</span>(horsepower<span class="sc">^</span><span class="dv">2</span>, mpg, <span class="at">pch =</span> <span class="dv">20</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-20-1.png" width="672" />
Looking at these plots, the relationship between <code>log(horsepower)</code> and <code>mpg</code> seems more linear.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="linear-regression.html#cb140-1" tabindex="-1"></a>lm.fitlog <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> . <span class="sc">-</span> name <span class="sc">+</span> <span class="fu">log</span>(horsepower), <span class="at">data =</span> Auto)</span>
<span id="cb140-2"><a href="linear-regression.html#cb140-2" tabindex="-1"></a>lm.fitnolog <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> . <span class="sc">-</span> name, <span class="at">data =</span> Auto)</span>
<span id="cb140-3"><a href="linear-regression.html#cb140-3" tabindex="-1"></a></span>
<span id="cb140-4"><a href="linear-regression.html#cb140-4" tabindex="-1"></a><span class="fu">anova</span>(lm.fitnolog, lm.fitlog)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: mpg ~ (cylinders + displacement + horsepower + weight + acceleration + 
##     year + origin + name) - name
## Model 2: mpg ~ (cylinders + displacement + horsepower + weight + acceleration + 
##     year + origin + name) - name + log(horsepower)
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    384 4252.2                                  
## 2    383 3354.0  1    898.19 102.56 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The ANOVA test shows that including the <code>log(horsepower)</code> term significantly improves the performance of the model.</p>
</div>
<div id="question-10-1" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Question 10<a href="linear-regression.html#question-10-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This question should be answered using the <code>Carseats</code> data set.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Fit a multiple regression model to predict <code>Sales</code> using <code>Price</code>, <code>Urban</code>,
and <code>US</code>.</p></li>
<li><p>Provide an interpretation of each coefficient in the model. Be
careful—some of the variables in the model are qualitative!</p></li>
<li><p>Write out the model in equation form, being careful to handle the
qualitative variables properly.</p></li>
<li><p>For which of the predictors can you reject the null hypothesis
<span class="math inline">\(H_0 : \beta_j = 0\)</span>?</p></li>
<li><p>On the basis of your response to the previous question, fit a smaller model
that only uses the predictors for which there is evidence of association
with the outcome.</p></li>
<li><p>How well do the models in (a) and (e) fit the data?</p></li>
<li><p>Using the model from (e), obtain 95% confidence intervals for the
coefficient(s).</p></li>
<li><p>Is there evidence of outliers or high leverage observations in the model
from (e)?</p></li>
</ol>
</blockquote>
</div>
<div id="question-11" class="section level3 hasAnchor" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> Question 11<a href="linear-regression.html#question-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>In this problem we will investigate the <em>t</em>-statistic for the null hypothesis
<span class="math inline">\(H_0 : \beta = 0\)</span> in simple linear regression without an intercept. To
begin, we generate a predictor <code>x</code> and a response <code>y</code> as follows.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="linear-regression.html#cb142-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb142-2"><a href="linear-regression.html#cb142-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb142-3"><a href="linear-regression.html#cb142-3" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li><p>Perform a simple linear regression of <code>y</code> onto <code>x</code>, <em>without</em> an intercept.
Report the coefficient estimate <span class="math inline">\(\hat{\beta}\)</span>, the standard error of this
coefficient estimate, and the <em>t</em>-statistic and _p_value associated with the
null hypothesis <span class="math inline">\(H_0 : \beta = 0\)</span>. Comment on these results. (You can
perform regression without an intercept using the command <code>lm(y~x+0)</code>.)</p></li>
<li><p>Now perform a simple linear regression of <code>x</code> onto <code>y</code> without an intercept,
and report the coefficient estimate, its standard error, and the
corresponding <em>t</em>-statistic and _p_values associated with the null hypothesis
<span class="math inline">\(H_0 : \beta = 0\)</span>. Comment on these results.</p></li>
<li><p>What is the relationship between the results obtained in (a) and (b)?</p></li>
<li><p>For the regression of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span> without an intercept, the
<em>t</em>-statistic for <span class="math inline">\(H_0 : \beta = 0\)</span> takes the form
<span class="math inline">\(\hat{\beta}/SE(\hat{\beta})\)</span>, where <span class="math inline">\(\hat{\beta}\)</span> is given by (3.38), and
where
<span class="math display">\[
SE(\hat\beta) = \sqrt{\frac{\sum_{i=1}^n(y_i - x_i\hat\beta)^2}{(n-1)\sum_{i&#39;=1}^nx_{i&#39;}^2}}.
\]</span>
(These formulas are slightly different from those given in Sections 3.1.1 and
3.1.2, since here we are performing regression without an intercept.) Show
algebraically, and confirm numerically in R, that the <em>t</em>-statistic can be
written as
<span class="math display">\[
\frac{(\sqrt{n-1}) \sum_{i-1}^nx_iy_i)}
     {\sqrt{(\sum_{i=1}^nx_i^2)(\sum_{i&#39;=1}^ny_{i&#39;}^2)-(\sum_{i&#39;=1}^nx_{i&#39;}y_{i&#39;})^2}}
\]</span></p></li>
<li><p>Using the results from (d), argue that the <em>t</em>-statistic for the
regression of y onto x is the same as the <em>t</em>-statistic for the regression
of <code>x</code> onto <code>y</code>.</p></li>
<li><p>In <code>R</code>, show that when regression is performed <em>with</em> an intercept, the
<em>t</em>-statistic for <span class="math inline">\(H_0 : \beta_1 = 0\)</span> is the same for the regression of <code>y</code>
onto <code>x</code> as it is for the regression of <code>x</code> onto <code>y</code>.</p></li>
</ol>
</blockquote>
</div>
<div id="question-12" class="section level3 hasAnchor" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> Question 12<a href="linear-regression.html#question-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This problem involves simple linear regression without an intercept.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Recall that the coefficient estimate <span class="math inline">\(\hat{\beta}\)</span> for the linear
regression of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span> without an intercept is given by (3.38). Under
what circumstance is the coefficient estimate for the regression of <span class="math inline">\(X\)</span>
onto <span class="math inline">\(Y\)</span> the same as the coefficient estimate for the regression of <span class="math inline">\(Y\)</span>
onto <span class="math inline">\(X\)</span>?</p></li>
<li><p>Generate an example in <code>R</code> with <span class="math inline">\(n = 100\)</span> observations in which the
coefficient estimate for the regression of <span class="math inline">\(X\)</span> onto <span class="math inline">\(Y\)</span> is different from
the coefficient estimate for the regression of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span>.</p></li>
<li><p>Generate an example in <code>R</code> with <span class="math inline">\(n = 100\)</span> observations in which the
coefficient estimate for the regression of <span class="math inline">\(X\)</span> onto <span class="math inline">\(Y\)</span> is the same as the
coefficient estimate for the regression of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span>.</p></li>
</ol>
</blockquote>
</div>
<div id="question-13" class="section level3 hasAnchor" number="3.2.6">
<h3><span class="header-section-number">3.2.6</span> Question 13<a href="linear-regression.html#question-13" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>In this exercise you will create some simulated data and will fit simple
linear regression models to it. Make sure to use <code>set.seed(1)</code> prior to
starting part (a) to ensure consistent results.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Using the <code>rnorm()</code> function, create a vector, <code>x</code>, containing 100
observations drawn from a <span class="math inline">\(N(0, 1)\)</span> distribution. This represents a
feature, <span class="math inline">\(X\)</span>.</p></li>
<li><p>Using the <code>rnorm()</code> function, create a vector, <code>eps</code>, containing 100
observations drawn from a <span class="math inline">\(N(0, 0.25)\)</span> distribution—a normal
distribution with mean zero and variance 0.25.</p></li>
<li><p>Using x and <code>eps</code>, generate a vector y according to the model
<span class="math display">\[Y = -1 + 0.5X + \epsilon\]</span>
What is the length of the vector <code>y</code>? What are the values of
<span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in this linear model?</p></li>
<li><p>Create a scatterplot displaying the relationship between <code>x</code> and <code>y</code>.
Comment on what you observe.</p></li>
<li><p>Fit a least squares linear model to predict <code>y</code> using <code>x</code>. Comment on the
model obtained. How do <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> compare to <span class="math inline">\(\beta_0\)</span>
and <span class="math inline">\(\beta_1\)</span>?</p></li>
<li><p>Display the least squares line on the scatterplot obtained in (d). Draw the
population regression line on the plot, in a different color. Use the
<code>legend()</code> command to create an appropriate legend.</p></li>
<li><p>Now fit a polynomial regression model that predicts <code>y</code> using <code>x</code> and <code>x^2</code>.
Is there evidence that the quadratic term improves the model fit? Explain
your answer.</p></li>
<li><p>Repeat (a)–(f) after modifying the data generation process in such a way
that there is <em>less</em> noise in the data. The model (3.39) should remain the
same. You can do this by decreasing the variance of the normal distribution
used to generate the error term <span class="math inline">\(\epsilon\)</span> in (b). Describe your results.</p></li>
<li><p>Repeat (a)–(f) after modifying the data generation process in such a way
that there is <em>more</em> noise in the data. The model (3.39) should remain the
same. You can do this by increasing the variance of the normal distribution
used to generate the error term <span class="math inline">\(\epsilon\)</span> in (b). Describe your results.</p></li>
<li><p>What are the confidence intervals for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> based on the
original data set, the noisier data set, and the less noisy data set?
Comment on your results.</p></li>
</ol>
</blockquote>
</div>
<div id="question-14" class="section level3 hasAnchor" number="3.2.7">
<h3><span class="header-section-number">3.2.7</span> Question 14<a href="linear-regression.html#question-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This problem focuses on the collinearity problem.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Perform the following commands in R :</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="linear-regression.html#cb143-1" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb143-2"><a href="linear-regression.html#cb143-2" tabindex="-1"></a><span class="sc">&gt;</span> x1 <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>)</span>
<span id="cb143-3"><a href="linear-regression.html#cb143-3" tabindex="-1"></a><span class="sc">&gt;</span> x2 <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">*</span> x1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>) <span class="sc">/</span> <span class="dv">10</span></span>
<span id="cb143-4"><a href="linear-regression.html#cb143-4" tabindex="-1"></a><span class="sc">&gt;</span> y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> x1 <span class="sc">+</span> <span class="fl">0.3</span> <span class="sc">*</span> x2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span></code></pre></div>
<p>The last line corresponds to creating a linear model in which <code>y</code> is a
function of <code>x1</code> and <code>x2</code>. Write out the form of the linear model. What are
the regression coefficients?</p></li>
<li><p>What is the correlation between <code>x1</code> and <code>x2</code>? Create a scatterplot
displaying the relationship between the variables.</p></li>
<li><p>Using this data, fit a least squares regression to predict <code>y</code> using <code>x1</code>
and <code>x2</code>. Describe the results obtained. What are <span class="math inline">\(\hat\beta_0\)</span>,
<span class="math inline">\(\hat\beta_1\)</span>, and <span class="math inline">\(\hat\beta_2\)</span>? How do these relate to the true <span class="math inline">\(\beta_0\)</span>,
<span class="math inline">\(\beta_1\)</span>, and _2$? Can you reject the null hypothesis <span class="math inline">\(H_0 : \beta_1\)</span>
= 0$? How about the null hypothesis <span class="math inline">\(H_0 : \beta_2 = 0\)</span>?</p></li>
<li><p>Now fit a least squares regression to predict <code>y</code> using only <code>x1</code>. Comment
on your results. Can you reject the null hypothesis <span class="math inline">\(H 0 : \beta_1 = 0\)</span>?</p></li>
<li><p>Now fit a least squares regression to predict <code>y</code> using only <code>x2</code>. Comment
on your results. Can you reject the null hypothesis <span class="math inline">\(H_0 : \beta_1 = 0\)</span>?</p></li>
<li><p>Do the results obtained in (c)–(e) contradict each other? Explain your
answer.</p></li>
<li><p>Now suppose we obtain one additional observation, which was unfortunately
mismeasured.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="linear-regression.html#cb144-1" tabindex="-1"></a><span class="sc">&gt;</span> x1 <span class="ot">&lt;-</span> <span class="fu">c</span>(x1, <span class="fl">0.1</span>)</span>
<span id="cb144-2"><a href="linear-regression.html#cb144-2" tabindex="-1"></a><span class="sc">&gt;</span> x2 <span class="ot">&lt;-</span> <span class="fu">c</span>(x2, <span class="fl">0.8</span>)</span>
<span id="cb144-3"><a href="linear-regression.html#cb144-3" tabindex="-1"></a><span class="sc">&gt;</span> y <span class="ot">&lt;-</span> <span class="fu">c</span>(y, <span class="dv">6</span>)</span></code></pre></div>
<p>Re-fit the linear models from (c) to (e) using this new data. What effect
does this new observation have on the each of the models? In each model, is
this observation an outlier? A high-leverage point? Both? Explain your
answers.</p></li>
</ol>
</blockquote>
</div>
<div id="question-15" class="section level3 hasAnchor" number="3.2.8">
<h3><span class="header-section-number">3.2.8</span> Question 15<a href="linear-regression.html#question-15" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This problem involves the <code>Boston</code> data set, which we saw in the lab for this
chapter. We will now try to predict per capita crime rate using the other
variables in this data set. In other words, per capita crime rate is the
response, and the other variables are the predictors.</p>
<ol style="list-style-type: lower-alpha">
<li><p>For each predictor, fit a simple linear regression model to predict the
response. Describe your results. In which of the models is there a
statistically significant association between the predictor and the
response? Create some plots to back up your assertions.</p></li>
<li><p>Fit a multiple regression model to predict the response using all of the
predictors. Describe your results. For which predictors can we reject the
null hypothesis <span class="math inline">\(H_0 : \beta_j = 0\)</span>?</p></li>
<li><p>How do your results from (a) compare to your results from (b)? Create a
plot displaying the univariate regression coefficients from (a) on the
<span class="math inline">\(x\)</span>-axis, and the multiple regression coefficients from (b) on the
<span class="math inline">\(y\)</span>-axis. That is, each predictor is displayed as a single point in the
plot. Its coefficient in a simple linear regression model is shown on the
x-axis, and its coefficient estimate in the multiple linear regression
model is shown on the y-axis.</p></li>
<li><p>Is there evidence of non-linear association between any of the predictors
and the response? To answer this question, for each predictor X, fit a
model of the form
<span class="math display">\[
Y = \beta_0 + \beta_1X + \beta_2X^2 + \beta_3X^3 + \epsilon
\]</span></p></li>
</ol>
</blockquote>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="statistical-learning.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="classification.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": {}
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fieldbox/ISLR2solutions/edit/main/03-linear-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
